name: React to Version Update

on:
  push:
    branches:
      - main  # Or your default branch
    paths:
      - DigMacro

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Print DigMacro content
        run: cat DigMacro
